"""v19 — same XGB+LGBM ensemble but trained on STABLE features only.

Step 1 identified 118 features whose distribution is stable across
benchmark and live data. v17 used all 355, half of which drift heavily.
By restricting v19 to stable features, we hope to recover discrimination
on live data without overfitting to benchmark artifacts.

Validation: compare v17 vs v19 on benchmark holdout AND on pseudo-labeled
live chunks (generated by v17 itself, so v17 has home-field advantage on
that set — improvement against pseudo-labels is therefore meaningful).
"""
from __future__ import annotations

import json
import pickle
import sys
import warnings
from pathlib import Path

import numpy as np

warnings.filterwarnings("ignore")
PROJECT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT))

from neurons.v14_features import extract_v14_features, V14_NAMES

DATA_DIR = PROJECT / "data" / "benchmark"
STABLE_PATH = PROJECT / "neurons" / "stable_features.json"
MODEL_OUTPUT = PROJECT / "neurons" / "model_v19.pkl"
PSEUDO_PATH = PROJECT / "neurons" / "pseudo_live_labels.json"
CAP_DIR = PROJECT / "neurons" / "captured_chunks_h2"


def load_benchmark():
    all_chunks, all_labels = [], []
    for f in sorted(DATA_DIR.glob("benchmark_*.json")):
        d = json.loads(f.read_text())
        for sc in d["data"]["chunks"]:
            sub_chunks = sc.get("chunks", [])
            gt = sc.get("groundTruth", [])
            assert len(sub_chunks) == len(gt)
            for c, lab in zip(sub_chunks, gt):
                all_chunks.append(c)
                all_labels.append(int(lab))
    return all_chunks, np.array(all_labels, dtype=np.int32)


def load_pseudo():
    pseudo = json.loads(PSEUDO_PATH.read_text())
    by_file = {}
    for p in pseudo:
        by_file.setdefault(p["file"], []).append((p["idx"], p["label"]))
    chunks, labels = [], []
    missing = 0
    for fname, items in by_file.items():
        path = CAP_DIR / fname
        if not path.exists():
            missing += len(items)
            continue
        d = json.loads(path.read_text())
        cap_chunks = d.get("chunks", [])
        for idx, lab in items:
            if idx < len(cap_chunks):
                chunks.append(cap_chunks[idx])
                labels.append(int(lab))
    if missing:
        print(f"  (skipped {missing} pseudo-labels from rotated capture files)")
    return chunks, np.array(labels, dtype=np.int32)


def extract(chunks):
    X = []
    for c in chunks:
        f = extract_v14_features(c) if c else np.zeros(355, dtype=np.float32)
        f = np.nan_to_num(f, nan=0.0, posinf=0.0, neginf=0.0)
        X.append(f)
    return np.array(X, dtype=np.float32)


def main():
    print("=" * 60)
    print("Poker44 v19 — stable-feature XGB+LGBM ensemble")
    print("=" * 60)

    stable = json.loads(STABLE_PATH.read_text())
    stable_idx = stable["stable_indices"]
    stable_names = [V14_NAMES[i] for i in stable_idx]
    print(f"using {len(stable_idx)} stable features (from 355)")

    # Benchmark data
    bench_chunks, bench_y = load_benchmark()
    print(f"benchmark chunks: {len(bench_chunks)} (bots={int(bench_y.sum())})")
    Xb = extract(bench_chunks)
    Xb_stable = Xb[:, stable_idx]

    # Pseudo-labeled live data — held out only, not used in training
    pseudo_chunks, pseudo_y = load_pseudo()
    print(f"pseudo-labeled live chunks: {len(pseudo_chunks)} (bots={int(pseudo_y.sum())})")
    Xp = extract(pseudo_chunks)
    Xp_stable = Xp[:, stable_idx]

    from sklearn.model_selection import train_test_split
    from sklearn.metrics import average_precision_score, confusion_matrix
    from sklearn.calibration import CalibratedClassifierCV
    from xgboost import XGBClassifier
    from lightgbm import LGBMClassifier

    X_tr, X_va, y_tr, y_va = train_test_split(
        Xb_stable, bench_y, test_size=0.20, random_state=42, stratify=bench_y
    )

    print(f"\nTrain: {X_tr.shape}  bots={int(y_tr.sum())}")
    print(f"Val:   {X_va.shape}  bots={int(y_va.sum())}")

    print("\n=== XGBoost ===")
    xgb = CalibratedClassifierCV(
        estimator=XGBClassifier(n_estimators=500, max_depth=5, learning_rate=0.04,
                                 subsample=0.85, colsample_bytree=0.7, min_child_weight=5,
                                 reg_alpha=0.3, reg_lambda=2.0, gamma=0.1,
                                 eval_metric="logloss", random_state=42, n_jobs=-1),
        method="isotonic", cv=5,
    )
    xgb.fit(X_tr, y_tr)
    p_xgb_va = xgb.predict_proba(X_va)[:, 1]
    ap_xgb = average_precision_score(y_va, p_xgb_va)
    print(f"  bench val AP={ap_xgb:.4f}")

    print("\n=== LightGBM ===")
    lgbm = CalibratedClassifierCV(
        estimator=LGBMClassifier(n_estimators=500, max_depth=6, learning_rate=0.04,
                                  subsample=0.85, colsample_bytree=0.7, min_child_samples=15,
                                  reg_alpha=0.3, reg_lambda=2.0, num_leaves=31,
                                  random_state=43, n_jobs=-1, verbose=-1),
        method="isotonic", cv=5,
    )
    lgbm.fit(X_tr, y_tr)
    p_lgbm_va = lgbm.predict_proba(X_va)[:, 1]
    ap_lgbm = average_precision_score(y_va, p_lgbm_va)
    print(f"  bench val AP={ap_lgbm:.4f}")

    best_w, best_ap = 0.5, 0.0
    for w in np.arange(0.2, 0.85, 0.05):
        ens = w * p_xgb_va + (1 - w) * p_lgbm_va
        ap = average_precision_score(y_va, ens)
        if ap > best_ap:
            best_ap, best_w = ap, w
    print(f"\n=== Ensemble (XGB w={best_w:.2f}) bench AP={best_ap:.4f} ===")

    # Now score the pseudo-labeled live set with v19 ensemble
    p_xgb_p = xgb.predict_proba(Xp_stable)[:, 1]
    p_lgbm_p = lgbm.predict_proba(Xp_stable)[:, 1]
    p_ens_p = best_w * p_xgb_p + (1 - best_w) * p_lgbm_p
    if pseudo_y.sum() > 0:
        ap_pseudo = average_precision_score(pseudo_y, p_ens_p)
        preds = (p_ens_p > 0.5).astype(int)
        tn, fp, fn, tp = confusion_matrix(pseudo_y, preds, labels=[0,1]).ravel()
        recall = tp / max(tp+fn, 1)
        fpr = fp / max(tn+fp, 1)
        print(f"\n=== Pseudo-live AP={ap_pseudo:.4f} recall={recall:.4f} fpr={fpr:.4f} ===")
    print(f"v19 pseudo-live bot scores: mean={p_ens_p[pseudo_y==1].mean():.4f}, "
          f"human scores: mean={p_ens_p[pseudo_y==0].mean():.4f}")

    payload = {
        "xgb_model": xgb, "lgbm_model": lgbm,
        "ensemble_weight_xgb": float(best_w),
        "feature_names": stable_names,
        "stable_indices": stable_idx,
        "version": 19, "training_size": int(len(y_tr)),
        "validation_ap": float(best_ap),
        "labels_method": "real-ground-truth (benchmark), stable-features only",
    }
    with open(MODEL_OUTPUT, "wb") as f:
        pickle.dump(payload, f)
    print(f"\nSaved {MODEL_OUTPUT} ({MODEL_OUTPUT.stat().st_size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
